<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9d020a1068656c6c6f776f726c642e70726f746f120a68656c6c6f776f" .
            "726c6422190a09486952657175657374120c0a046e616d65180120012809" .
            "221a0a0748695265706c79120f0a076d657373616765180120012809221c" .
            "0a0c48656c6c6f52657175657374120c0a046e616d65180120012809221d" .
            "0a0a48656c6c6f5265706c79120f0a076d65737361676518012001280932" .
            "80010a074772656574657212350a05536179486912152e68656c6c6f776f" .
            "726c642e4869526571756573741a132e68656c6c6f776f726c642e486952" .
            "65706c792200123e0a0853617948656c6c6f12182e68656c6c6f776f726c" .
            "642e48656c6c6f526571756573741a162e68656c6c6f776f726c642e4865" .
            "6c6c6f5265706c792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

