-- for SqlLogTarget
CREATE TABLE `sql_log` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `app` char(32) NOT NULL DEFAULT '',
  `request_uri` varchar(500) DEFAULT NULL,
  `trace_file` varchar(2000) DEFAULT NULL,
  `trace_sql` varchar(10000) DEFAULT NULL,
  `extra` text,
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE people(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(32) NOT NULL DEFAULT '' COMMENT '名字',
  sex TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '性别 0:女 1:男',
  age TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT '年龄',
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;